# Tomado desde https://hub.docker.com/r/library/python/tags/
FROM python:slim-buster

# Crear archivo src/app en /usr
RUN mkdir /usr/src/app/

# Copiar src/app al contenedor
COPY src/app /usr/src/app

# Instalar flask
RUN pip install flask

# Configurar el workdir
WORKDIR /usr/src/app

# Exponer el puerto 8000
EXPOSE 8000

# Comandos a llamar
CMD ["python", "app.py"]